config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # ideas
  resources :ideas do
    resources :likes, only: [:create, :destroy]
    resources :joins, only: [:create, :destroy]
  end

  # joins
  # This is to have a page showing joined users
  resources :joins, only: [:index]

  # users
  resources :users, only: [:create, :new]

  # sessions
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "ideas#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    can :manage, Idea do |i|
      i.user == user
    end
  end
end

app/models/concerns/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, Idea
    can :manage, Idea, :user_id => user.id
    cannot :create, Like, :user_id => user.id

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/concerns/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :memberships
  has_many :users, through: :memberships, source: :user

  validates :title, presence: true, uniqueness: true, length: { minimum: 5 }
  validates :description, presence: true
end

app/models/concerns/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea


  validates :user_id, presence: true
  validates :idea_id, presence: true, uniqueness: { scope: :user_id }
end

app/models/concerns/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates :user_id, presence: true
  validates :idea_id, presence: true, uniqueness: { scope: :user_id }
end

app/models/concerns/user.rb
class User < ActiveRecord::Base
  has_many :ideas, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :idea_groups, through: :memberships, source: :idea

  has_secure_password

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  has_many :joins, dependent: :destroy
  has_many :joined_users, through: :joins, source: :user

  validates :title, presence: true, uniqueness: true

  # Uses the full name method defined in the users model.
  def user_full_name
    user.full_name if user
  end

  def like_for(user)
    likes.find_by_user_id(user)
  end

  def join_for(user)
    joins.find_by_user_id(user)
  end
end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates :user_id, :idea_id, presence: true
  validates :user_id, uniqueness: {scope: :idea_id}

  validate :users_cant_join_their_ideas

  private

  def users_cant_join_their_ideas
    return if user.nil? or idea.nil?
    if user_id == idea.user_id
      errors[:base] = "Users can't join their own ideas"
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates :user_id, :idea_id, presence: true
  validates :user_id, uniqueness: {scope: :idea_id}

  validate :users_cant_like_their_ideas

  private

  def users_cant_like_their_ideas
    return if user.nil? or idea.nil?
    if user_id == idea.user_id
      errors[:base] = "Users can't like their own ideas"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ideas, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea

  has_many :joins, dependent: :destroy
  has_many :joined_ideas, through: :joins, source: :idea

  has_secure_password

  validates :password, length: {minimum: 6}, on: :create
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id].present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if user_signed_in?
  end
  helper_method :current_user

  def sign_in(user)
    session[:user_id] = user.id
  end


  def authenticate_user
    redirect_to new_session_path, notice: "Please sign in." unless user_signed_in?
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.order(:updated_at, :created_at)
  end

  def show
    @idea = Idea.find params[:id]
  end

  def edit
    @idea = Idea.find params[:id]

    redirect_to root_path unless can? :manage, @idea
  end

  def update
    @idea = Idea.find params[:id]

    redirect_to root_path unless can? :manage, @idea

    if @idea.update idea_params
      redirect_to idea_path @idea
    else
      redirect_to root_path
    end
  end

  def destroy
    @idea = Idea.find params[:id]

    redirect_to root_path unless can? :manage, @idea

    if @idea.destroy
      redirect_to root_path
    else
      render @idea
    end
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user_id = current_user.id

    if @idea.save
      redirect_to idea_path @idea
    else
      redirect_to root_path
    end

  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.user = User.find params[:user_id]
    @like.idea = Idea.find params[:idea_id]

    @like.save
    redirect_to root_path
  end

  def destroy
    @user = current_user
    @idea = Idea.find params[:idea_id]
    @like = Like.find_by_user_id_and_idea_id(@user, @idea)

    @like.destroy
    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_idea_form.html.erb
<%= form_for [current_user, @idea] do |f| %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title, size: 75 %>
  </div>

  <div>
    <%= f.text_area :description, size: '80x24' %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/ideas/edit.html.erb
<h2>Edit Idea</h2>

<%= render 'idea_form' %>

app/views/ideas/index.html.erb
<h2>All Ideas</h2>

<ol>
  <% @ideas.each do |idea| %>
  <li>
    <h3><%= link_to idea.title, idea_path(idea) %></h3>
    <p><%= idea.description %></p>
    <p><%= "By #{idea.user.name}" %></p>

    <%# LIKES %>
    <% like = Like.find_by_user_id_and_idea_id(current_user, idea) %>
    <% if like.present? %>
      <%= button_to 'Unlike', user_idea_likes_path(current_user.id, idea.id, like: {user_id: current_user.id, idea: idea.id}), method: :delete %>
    <% else %>
      <%= button_to 'Like', user_idea_likes_path(current_user.id, idea.id, like: {user_id: current_user.id, idea: idea.id}), method: :post %>
    <% end %>

    <%# MEMBERS %>
    <% if idea.users.include? current_user %>
      <%#= button_to 'Joined', user_idea_path %>
    <% else %>
      <%= button_to 'Join', user_idea_path(current_user, idea) %>
    <% end %>

    <p>Likes: <%= idea.likes.count %></p>
    <p>Members: <%= idea.users.count %></p>
    <hr>
  </li>
  <% end %>

</ol>

app/views/ideas/new.html.erb
<h2>New Idea</h2>

<%= render 'idea_form' %>

app/views/ideas/show.html.erb
<h2><%= @idea.title %></h2>

<p><%= @idea.description %></p>

<p>Likes: <%= @idea.likes.count %></p>


<% if can? :update, @idea %>
  <%= link_to "Edit", edit_user_idea_path(@idea.user_id, @idea) %>
<% end %>

<% if can? :destroy, @idea %>
  <%= link_to "Delete", user_idea_path(@idea.user_id, @idea), method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Idea Factory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Idea Factory</h1>

<%= link_to 'All Ideas', root_path %>

<% if session[:user_id] %>
  Hello, <%= (User.find session[:user_id]).name %>
  <%= link_to 'New Idea', new_user_idea_path(current_user) %>
  <%= link_to 'Sign out', sessions_path, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_session_path %>
<% end %>

<hr>

<%= yield %>

</body>
</html>